api_version = "2025-10"

[[extensions]]
name = "t:name"
#[START validation-settings.handle-name-ui]
handle = "product-limits-function-ui"
#[END validation-settings.handle-name-ui]
type = "ui_extension"
uid = "81136fe0-112a-9eba-b3e3-1e8d47ffaec836dff13a"

[[extensions.targeting]]
module = "./src/ValidationSettings.jsx"
target = "admin.settings.validation.render"
